<?php

use App\Actions\Accounting\ReverseJournalEntry;
use App\Enums\AccountSubtype;
use App\Exceptions\Posting\PeriodLockedException;
use App\Models\Company;
use App\Models\JournalEntry;
use App\Models\TaxCode;
use App\Services\Posting\JournalPoster;
use App\Support\Reporting\SourceLinkResolver;
use Carbon\CarbonImmutable;
use Flux\Flux;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Title;
use Livewire\Component;

new #[Title('Journal entry')] class extends Component {
    public Company $company;

    public JournalEntry $entry;

    public string $reverseDate = '';

    public ?string $sourceUrl = null;

    public string $sourceLabel = '';

    public ?string $duplicateUrl = null;

    public function mount(Company $company, JournalEntry $entry): void
    {
        $this->company = $company;
        $this->entry = $entry->load('lines.account', 'reversedBy', 'reverses');

        if ($this->isSourceLinked()) {
            $resolver = app(SourceLinkResolver::class);
            $this->sourceUrl = $resolver->urlFor($entry, $company);
            $this->sourceLabel = $resolver->label($entry);
            // Duplicate the originating document, not a manual copy of its GL entry.
            $this->duplicateUrl = $resolver->duplicateUrlFor($entry, $company);
        } else {
            $this->duplicateUrl = route('journal.create', ['company' => $company->slug, 'from' => $entry->id]);
        }

        // Default a reversal to the first day of the month after the entry — the
        // common accrual case — while leaving the date editable.
        $this->reverseDate = CarbonImmutable::parse($entry->entry_date)
            ->startOfMonth()
            ->addMonth()
            ->toDateString();
    }

    /**
     * Whether this entry was generated by another document (Deposit, Invoice, …).
     * Most such entries are read-only from the general journal; the exceptions
     * (a reconciliation's service charge / interest) allow a header-only edit —
     * see JournalEntry::isEditableInJournal().
     */
    public function isSourceLinked(): bool
    {
        return $this->entry->source_type !== null;
    }

    /**
     * Codes for any tax codes tagged on the lines, keyed by id. The tag is for
     * tax reporting only — no amounts are derived from it. Empty when no line
     * carries one, which hides the column entirely.
     *
     * @return array<int, string>
     */
    #[Computed]
    public function lineTaxCodes(): array
    {
        $ids = $this->entry->lines->pluck('tax_code_id')->filter()->unique();

        if ($ids->isEmpty()) {
            return [];
        }

        return TaxCode::withoutGlobalScopes()->whereIn('id', $ids)->pluck('code', 'id')->all();
    }

    public function void(JournalPoster $poster): void
    {
        abort_if($this->isSourceLinked(), 403);

        try {
            $poster->void($this->entry);
        } catch (PeriodLockedException $e) {
            Flux::toast(variant: 'danger', text: $e->getMessage());

            return;
        }

        Flux::toast(variant: 'success', text: __('Entry voided.'));
        $this->redirectRoute('journal.index', ['company' => $this->company->slug], navigate: true);
    }

    /**
     * Create a draft accrual reversal of this posted entry and open it for review.
     * The original stays posted (this is not a void).
     */
    public function reverse(ReverseJournalEntry $action): void
    {
        abort_unless($this->entry->isPosted() && ! $this->entry->isVoided(), 403);
        abort_if($this->isSourceLinked(), 403);

        $this->validate(['reverseDate' => ['required', 'date']]);

        $reversal = $action->handle($this->entry, CarbonImmutable::parse($this->reverseDate));

        Flux::toast(variant: 'success', text: __('Draft reversal :no created. Review and post it.', ['no' => $reversal->entry_no]));
        $this->redirectRoute('journal.edit', ['company' => $this->company->slug, 'entry' => $reversal->id], navigate: true);
    }
}; ?>

<section class="w-full">
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
            <flux:heading size="xl" level="1">{{ __('Entry') }} {{ $entry->entry_no }}</flux:heading>
            <flux:subheading>{{ $entry->entry_date->toDateString() }} &middot; {{ $entry->memo }}</flux:subheading>
            <div class="mt-2 hidden items-center gap-2 lg:flex">
                @if ($entry->isVoided())
                    <flux:badge color="zinc">{{ __('Voided') }}</flux:badge>
                @elseif ($entry->isPosted())
                    <flux:badge color="green">{{ __('Posted') }}</flux:badge>
                @else
                    <flux:badge color="amber">{{ __('Draft') }}</flux:badge>
                @endif

                @if ($entry->reverses_entry_id)
                    <flux:badge color="zinc">
                        {{ __('Reverses') }}
                        <a href="{{ route('journal.show', ['company' => $company->slug, 'entry' => $entry->reverses_entry_id]) }}" wire:navigate class="underline">#{{ $entry->reverses_entry_id }}</a>
                    </flux:badge>
                @endif

                @if ($entry->reversed_by_entry_id)
                    <flux:badge color="zinc">
                        {{ __('Reversed by') }}
                        <a href="{{ route('journal.show', ['company' => $company->slug, 'entry' => $entry->reversed_by_entry_id]) }}" wire:navigate class="underline">#{{ $entry->reversed_by_entry_id }}</a>
                    </flux:badge>
                @endif

                @if ($entry->source_type !== null)
                    <flux:badge color="blue" icon="link">
                        {{ __('Source') }}:
                        @if ($sourceUrl)
                            <a href="{{ $sourceUrl }}" wire:navigate class="underline">{{ $sourceLabel }}</a>
                        @else
                            {{ $sourceLabel }}
                        @endif
                    </flux:badge>
                @endif
            </div>
        </div>

        @php($canEdit = $entry->isEditableInJournal() && ! $entry->isVoided())
        <div class="flex flex-wrap items-center gap-2">
            @if ($entry->source_type !== null && $sourceUrl)
                <flux:button
                    :variant="$canEdit ? 'filled' : 'primary'"
                    class="!hidden lg:!inline-flex"
                    :href="$sourceUrl"
                    wire:navigate
                    data-test="view-source-button"
                >
                    {{ __('View :source', ['source' => $sourceLabel]) }}
                </flux:button>
            @endif
            @if ($canEdit)
                <flux:button
                    variant="primary"
                    class="!hidden lg:!inline-flex"
                    :href="route('journal.edit', ['company' => $company->slug, 'entry' => $entry->id])"
                    wire:navigate
                    data-test="edit-entry-button"
                >
                    {{ __('Edit') }}
                </flux:button>
            @endif

            <flux:dropdown align="end">
                <flux:button icon:trailing="chevron-down" data-test="journal-actions-menu">{{ __('Actions') }}</flux:button>
                <flux:menu>
                    @if ($entry->source_type !== null && $sourceUrl)
                        <flux:menu.item class="lg:hidden" icon="link" :href="$sourceUrl" wire:navigate data-test="view-source-menu-item">
                            {{ __('View :source', ['source' => $sourceLabel]) }}
                        </flux:menu.item>
                    @endif
                    @if ($canEdit)
                        <flux:menu.item class="lg:hidden" icon="pencil" :href="route('journal.edit', ['company' => $company->slug, 'entry' => $entry->id])" wire:navigate data-test="edit-entry-menu-item">
                            {{ __('Edit') }}
                        </flux:menu.item>
                    @endif
                    @if ($duplicateUrl)
                        <flux:menu.item icon="document-duplicate" :href="$duplicateUrl" wire:navigate data-test="duplicate-entry-button">
                            {{ __('Duplicate') }}
                        </flux:menu.item>
                    @endif
                    <flux:menu.item icon="arrow-path" :href="route('recurring-journal.create', ['company' => $company->slug, 'from' => $entry->id])" wire:navigate data-test="memorize-entry-button">
                        {{ __('Memorize') }}
                    </flux:menu.item>
                    @if ($entry->isPosted() && ! $entry->isVoided() && $entry->source_type === null)
                        <flux:menu.separator />
                        <flux:modal.trigger name="reverse-entry">
                            <flux:menu.item icon="arrow-uturn-left" data-test="reverse-entry-button">
                                {{ __('Reverse') }}
                            </flux:menu.item>
                        </flux:modal.trigger>
                        <flux:menu.item icon="x-circle" variant="danger" wire:click="void" wire:confirm="{{ __('Void this entry? A reversing entry will be posted.') }}" data-test="void-entry-button">
                            {{ __('Void') }}
                        </flux:menu.item>
                    @endif
                </flux:menu>
            </flux:dropdown>
        </div>
    </div>

    @if ($entry->isPosted() && ! $entry->isVoided() && $entry->source_type === null)
        <flux:modal name="reverse-entry" focusable class="max-w-md">
            <form wire:submit="reverse" class="space-y-6">
                <div>
                    <flux:heading size="lg">{{ __('Reverse entry') }}</flux:heading>
                    <flux:subheading>{{ __('Creates a draft entry with debits and credits swapped. The original entry stays posted. Review and post the reversal yourself.') }}</flux:subheading>
                </div>

                <flux:input
                    type="date"
                    wire:model="reverseDate"
                    :label="__('Reversal date')"
                    required
                    data-test="reverse-entry-date"
                />

                <div class="flex justify-end space-x-2 rtl:space-x-reverse">
                    <flux:modal.close>
                        <flux:button variant="filled">{{ __('Cancel') }}</flux:button>
                    </flux:modal.close>
                    <flux:button variant="primary" type="submit" data-test="reverse-entry-submit">{{ __('Create draft reversal') }}</flux:button>
                </div>
            </form>
        </flux:modal>
    @endif

    @php($showTaxCodes = $this->lineTaxCodes !== [])
    <div class="overflow-x-auto rounded-lg border border-border">
        <table class="w-full text-sm">
            <thead class="bg-muted">
                <tr>
                    <th class="px-4 py-2 text-left font-medium">{{ __('Account') }}</th>
                    <th class="px-4 py-2 text-left font-medium">{{ __('Memo') }}</th>
                    @if ($showTaxCodes)
                        <th class="px-4 py-2 text-left font-medium">{{ __('Tax code') }}</th>
                    @endif
                    <th class="px-4 py-2 text-right font-medium">{{ __('Debit') }}</th>
                    <th class="px-4 py-2 text-right font-medium">{{ __('Credit') }}</th>
                    <th class="px-4 py-2"></th>
                </tr>
            </thead>
            <tbody class="divide-y divide-border">
                @foreach ($entry->lines as $line)
                    <tr data-test="entry-show-line">
                        <td class="px-4 py-2">{{ $line->account->code }} — {{ $line->account->name }}</td>
                        <td class="px-4 py-2 text-muted-foreground">{{ $line->memo }}</td>
                        @if ($showTaxCodes)
                            <td class="px-4 py-2 text-muted-foreground" data-test="line-tax-code">{{ $this->lineTaxCodes[$line->tax_code_id] ?? '' }}</td>
                        @endif
                        <td class="px-4 py-2 text-right font-mono">{{ $line->debit_cents > 0 ? number_format($line->debit_cents / 100, 2) : '' }}</td>
                        <td class="px-4 py-2 text-right font-mono">{{ $line->credit_cents > 0 ? number_format($line->credit_cents / 100, 2) : '' }}</td>
                        <td class="px-4 py-2 text-right">
                            @if ($line->account->subtype === AccountSubtype::FixedAsset && $line->debit_cents > 0)
                                <flux:tooltip :content="__('Create asset record')">
                                    <flux:button
                                        variant="ghost"
                                        size="sm"
                                        icon="cube"
                                        :href="route('assets.create', ['company' => $company->slug, 'source_type' => 'journal_line', 'source_id' => $line->id])"
                                        wire:navigate
                                        data-test="create-asset-from-journal-line"
                                    />
                                </flux:tooltip>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot class="bg-muted">
                <tr>
                    <td colspan="{{ $showTaxCodes ? 3 : 2 }}" class="px-4 py-2 text-right font-medium">{{ __('Totals') }}</td>
                    <td class="px-4 py-2 text-right font-mono">{{ number_format($entry->totalDebitsCents() / 100, 2) }}</td>
                    <td class="px-4 py-2 text-right font-mono">{{ number_format($entry->totalCreditsCents() / 100, 2) }}</td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="mt-6">
        <livewire:audit-trail
            :auditable-type="$entry->getMorphClass()"
            :auditable-id="$entry->id"
        />
    </div>
</section>
